remote_theme: samanyougarg/hanuman

# Site settings
title: Ricky & Lucky
description: perfect pets for life 
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "" # the subpath of your site, e.g. /blog/ or "" for root
url: "http://gretaf.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
